import Head from 'next/head';
import Header from 'public/images/header.svg';
import Banner from 'public/images/banner.svg';
import Footer from 'public/images/footer.svg';
import home from 'public/images/Home.png';
import { useEffect } from 'react';
import Image from 'next/image';

export default function HomePage() {

  useEffect(() => {
    window.onscroll = e => {
      console.log(window.scrollY);
      if (window.scrollY > 60) {
        document.getElementById('headerfixed').style.transform = 'translateY(0)';
      } else {
        document.getElementById('headerfixed').style.transform = 'translateY(-100%)';
      }
    }

    return () => window.onscroll = null;
  }, []);

  return (
    <>
      <Head>
        <title>Embasul</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main>
        <Header style={{
          width: 'calc(100vw + 12px)',
          height: 'auto',
          position: 'fixed',
          left: '-12px',
          top: '-12px',
          transform: 'translateY(-100%)',
          transition: '400ms',
        }}
          id="headerfixed"
        />

        <Banner style={{ width: '100%', height: 'auto', }} />

        <Image quality={100} style={{ width: '100%', height: 'auto', objectPosition: 'top', objectFit: 'cover' }} src={home} />

        <Footer style={{ width: '100%', height: 'auto', }} />
      </main>
    </>
  )
}
